/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.LogicaTarea;

public class DlgEditar extends javax.swing.JDialog {

    /**
     * Creates new form DlgEditar
     * @param parent
     * @param modal
     */
    public DlgEditar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurar();
        llenarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNvTarea = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnChngStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tarea");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtNvTarea.setText("proximamente...");
        getContentPane().add(txtNvTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 290, -1));

        btnActualizar.setText("actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jButton2.setText("borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        btnChngStatus.setText("completado");
        btnChngStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChngStatusActionPerformed(evt);
            }
        });
        getContentPane().add(btnChngStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actDatos(1);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnChngStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChngStatusActionPerformed
        chngStatus();
    }//GEN-LAST:event_btnChngStatusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        brrTarea();
    }//GEN-LAST:event_jButton2ActionPerformed

    //borrar una tarea
    private void brrTarea(){
        LogicaTarea.brrTarea(indice);
        this.dispose(); //cerrar jdialogform
        panelPri.verTarea();
    }

    //cambiar status de tarea
    private void chngStatus(){
        actDatos(2);
    }

    //actualizar tarea
    private void actDatos(int opc){
        switch(opc){
            case 1 ->{
                LogicaTarea.edtTarea(txtNvTarea.getText(), status, indice);
                this.dispose(); //cerrar jdialogform
                panelPri.verTarea();
            }
            case 2 ->{
                LogicaTarea.edtTarea(null, status, indice);
                this.dispose(); //cerrar jdialogform
                panelPri.verTarea();
            }
            default -> System.out.println("opcion invalida");
        }
    }

    //llenar datos
    private void llenarDatos(){
        txtNvTarea.setText(textoTarea);
        btnChngStatus.setText(status?"Pendiente":"Completar");
    }

    //metodo para traer datos
    public static void envDato(String tarea, boolean stt, int i){
        textoTarea=tarea;
        status=stt;
        indice=i;
    }
    
    //metodo para traer el objeto PnlPrincipal
    public static void envPanel(PnlPrincipal pp){
        panelPri=pp;
    }
    
    //variables auxiliares
    private static String textoTarea;
    private static boolean status;
    private static int indice;
    private static PnlPrincipal panelPri;

    //configurar esto
    private void configurar(){
        setTitle("Editando Tarea");
        txtNvTarea.setText(null);
        setLocationRelativeTo(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnChngStatus;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNvTarea;
    // End of variables declaration//GEN-END:variables
}
