
package View;

import Controller.LogicaTarea;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class PnlPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PnlAnadir
     */
    public PnlPrincipal() {
        initComponents();
        configurarTabla();
        verTarea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTarea = new javax.swing.JTextField();
        btnAnadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(330, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nueva Tarea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        add(txtTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 400, -1));

        btnAnadir.setText("agregar");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLista);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 600, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        if(verificar(txtTarea)){
            enviarTarea();
            verTarea();
        }else{
            txtTarea.setText(null);
            //mensaje de campo vacio
            JOptionPane.showMessageDialog(this, "Entrada no valida.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void tblListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaMouseClicked
        filcol(evt);
    }//GEN-LAST:event_tblListaMouseClicked
    
    //obtener fila y columna clickeada
    private void filcol(java.awt.event.MouseEvent evt){
        int fila=tblLista.rowAtPoint(evt.getPoint());
        int columna=tblLista.columnAtPoint(evt.getPoint());
        if(columna==2){
            //enviar los datos al jdialogform
            DlgEditar.envDato(LogicaTarea.verTarea().get(fila).get(0), LogicaTarea.verTarea().get(fila).get(1).equals("true"), fila);
            //invocar la ventana de editar
            DlgEditar ventEdit=new DlgEditar(ventHome, true);
            ventEdit.setVisible(true);
            
        }
    }
    
    //recibe el objeto Home y llena la variable del padre
    public static void padre(Home componente){
        ventHome=componente;
    }
    //variable del padre
    private static Home ventHome;

    //funcion para añadir tareas
    private void enviarTarea(){
        LogicaTarea.anadirTarea(txtTarea.getText(), false);
        txtTarea.setText(null);
    }
    
    //crear modelo de la tabla
    private final DefaultTableModel model=new DefaultTableModel(){
        //para evitar que las celdas sean editables
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        
    };
    
    //configura la tabla
    private void configurarTabla(){
        //configurar encabezado
        for (String enc : LogicaTarea.envEncabezado()) {
            model.addColumn(enc);
        }
        
        
        //asignar modelo
        tblLista.setModel(model);
        
        //configurar otras partes
        tblLista.getTableHeader().setReorderingAllowed(false);
        tblLista.setSize(600, 430);
        //confiurar columna
        tblLista.getColumnModel().getColumn(0).setPreferredWidth(460);
        tblLista.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblLista.getColumnModel().getColumn(2).setPreferredWidth(60);
        tblLista.getColumnModel().getColumn(0).setResizable(false);
        tblLista.getColumnModel().getColumn(1).setResizable(false);
        tblLista.getColumnModel().getColumn(2).setResizable(false);
        //centrar columnas
        DefaultTableCellRenderer centrado=new DefaultTableCellRenderer();
        centrado.setHorizontalAlignment(SwingConstants.CENTER);
        tblLista.getColumnModel().getColumn(1).setCellRenderer(centrado);
        tblLista.getColumnModel().getColumn(2).setCellRenderer(centrado);
    }
    
    //verificar entrada de tareas
    private boolean verificar(JTextField campo){
        return !(campo.getText().isBlank());
        
    }
    
    //funcion para listar las tareas
    public void verTarea(){
        model.setRowCount(0); //limpiar tabla
        for (ArrayList<String> fila : LogicaTarea.verTarea()) {
            model.addRow(new String[]{fila.get(0), fila.get(1).equals("true")?"¡Listo!":"Aun no...", "¿editar?"});
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtTarea;
    // End of variables declaration//GEN-END:variables
}
