
package View;

import Controller.LogicaTarea;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class PnlPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PnlAnadir
     */
    public PnlPrincipal() {
        initComponents();
        configurarTabla();
        verTarea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTarea = new javax.swing.JTextField();
        btnAnadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(330, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nueva Tarea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        add(txtTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, -1));

        btnAnadir.setText("...");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 30, -1));

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLista);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 310, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        enviarTarea();
        verTarea();
    }//GEN-LAST:event_btnAnadirActionPerformed
    
    private void enviarTarea(){
        new LogicaTarea().anadirTarea(txtTarea.getText(), false);
    }
    
    //crear modelo de la tabla
    DefaultTableModel model=new DefaultTableModel();
    private void configurarTabla(){
        //configurar encabezado
        for (String enc : LogicaTarea.envEncabezado()) {
            model.addColumn(enc);
        }
        
        //asignar modelo
        tblLista.setModel(model);
        
        //configurar otras partes
        tblLista.getTableHeader().setReorderingAllowed(false);
        tblLista.setSize(310, 490);
    }
    
    private void verTarea(){
        model.setRowCount(0); //limpiar tabla
        for (ArrayList<String> fila : LogicaTarea.verTarea()) {
            model.addRow(new String[]{"a","b","c","d"});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtTarea;
    // End of variables declaration//GEN-END:variables
}
